### PR TITLE
add elevator area to eng2-3f's map

### PR DESCRIPTION
**Pull request by mqcmd196**
I add elevator map at 3F.

`eng2-3f-0.05_keepout.xcf`
I finally deleted the elevator layer like `eng2-7f-0.05_keepout.xcf`. 
transparency 50%
Screenshot from 2020-09-29 18-53-20
layer info
Screenshot from 2020-09-29 19-01-57

I couldn't preview pgm file here, so please check `eng2-3f-0.05pgm` and `eng2-3f-0.05_keepout.pgm` directly.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
@mqcmd196 
Thanks. Good PR.
Elevator maps are needed for the robot to exit the elevator autonomously.

However, there appears to be an editing error at the top of the image after editing. 
 (The same goes for keepout map.)

|Before|This PR|
|---|---|
|||

**Comment by knorth55** [comment]
something seems wrong with stairs at the top center.
you maybe mistook to copy & paste elevator there.

**Comment by mqcmd196** [comment]
Woops, I think something went wrong and failed to paste correctly. I'll fix and commit here. Thanks!

**Comment by mqcmd196** [comment]
@708yamaguchi @knorth55 Would you review it again?

**Comment by 708yamaguchi** [comment]
LGTM
Thank you!

**Pull request merged**
